#!/usr/bin/env bash
# Pre-commit runs-immutability gate (WS-314). Blocks edits to sealed engine-
# run artifacts. A run is sealed once an `engine_run_completed` event has
# been emitted for it. Sealed paths:
#   .claude/workstream/runs/<run-id>/manifest.yaml
#   .claude/workstream/runs/<run-id>/artifacts/**
#
# Updates to a sealed run flow through:
#   .claude/workstream/runs/<run-id>/addendum.md   (free to add or modify)
#   .claude/workstream/runs/<run-id>/summary.yaml  (regenerated by reconcile)
#
# See: kit/templates/workstream/runs/CANONICAL.md
#
# Install via: bash kit/scripts/install-git-hooks.sh

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
CHECKER="$REPO_ROOT/kit/scripts/cwos-runs-sealed.js"

# Skip silently on repos that haven't adopted WS-314 yet.
if [ ! -f "$CHECKER" ]; then exit 0; fi

# Collect staged sealed-path candidates: manifest.yaml or anything under
# artifacts/. Excludes addendum.md and summary.yaml (the explicit escape
# hatches). Diff-filter ACMR catches add/copy/modify/rename; deletes are
# also blocked because losing a sealed artifact violates canonicality.
STAGED=$(git diff --cached --name-only --diff-filter=ACMRD \
  | grep -E '^\.claude/workstream/runs/run-[^/]+/(manifest\.yaml|artifacts/)' || true)

if [ -z "$STAGED" ]; then exit 0; fi

# Extract unique run-ids from the staged paths.
RUN_IDS=$(echo "$STAGED" \
  | sed -E 's|^\.claude/workstream/runs/(run-[^/]+)/.*$|\1|' \
  | sort -u \
  | paste -sd, -)

if [ -z "$RUN_IDS" ]; then exit 0; fi

# Ask the checker which of those run-ids are sealed. It exits 1 with a
# newline-separated list on stdout when at least one is sealed.
SEALED_OUTPUT=$(node "$CHECKER" --run-ids "$RUN_IDS" 2>/tmp/cwos-runs-sealed-stderr || true)
SEALED_EXIT=$?

if [ "$SEALED_EXIT" -eq 0 ]; then
  rm -f /tmp/cwos-runs-sealed-stderr
  exit 0
fi

if [ "$SEALED_EXIT" -ne 1 ]; then
  echo "pre-commit-runs-immutability: checker error (exit $SEALED_EXIT)" >&2
  cat /tmp/cwos-runs-sealed-stderr >&2 2>/dev/null || true
  rm -f /tmp/cwos-runs-sealed-stderr
  exit 1
fi

echo "" >&2
echo "ERROR — sealed engine-run artifacts cannot be modified (WS-314)." >&2
echo "" >&2
echo "Sealed runs in this commit:" >&2
echo "$SEALED_OUTPUT" | sed 's/^/  - /' >&2
echo "" >&2
echo "Affected staged paths:" >&2
echo "$STAGED" | sed 's/^/  /' >&2
echo "" >&2
echo "To record updates to a sealed run, edit (or add):" >&2
echo "  .claude/workstream/runs/<run-id>/addendum.md" >&2
echo "" >&2
echo "Schema: kit/templates/workstream/runs/CANONICAL.md" >&2
rm -f /tmp/cwos-runs-sealed-stderr
exit 1
